module.exports = {
  PHASES: {
    LOBBY: 'LOBBY',
    WORD_SELECT: 'WORD_SELECT',
    DRAWING: 'DRAWING',
    REVIEW: 'REVIEW',
    PODIUM: 'PODIUM'
  },
  WORD_SELECT_TIME_MS: 15000,
  REVIEW_TIME_MS: 7000,
  RECONNECT_GRACE_MS: 30000,
  PUBLIC_ROOM_CAP: 8,
  MIN_ROUNDS: 2,
  MAX_ROUNDS: 10,
  MIN_DRAW_TIME: 30,
  MAX_DRAW_TIME: 180,
  DEFAULT_ROUNDS: 3,
  DEFAULT_DRAW_TIME: 80,
  HEARTBEAT_INTERVAL_MS: 2000,
  MAX_PLAYERS_PRIVATE: 12,
  WORD_OPTIONS_COUNT: 3,
  HINT_THRESHOLDS: [0.75, 0.5, 0.25] // fraction of time remaining at which another letter is revealed
};
